/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SignRouteImport } from './routes/sign'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin/route'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedSettingsRouteRouteImport } from './routes/_authed/settings/route'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedAdminAuditRouteImport } from './routes/_authed/admin/audit'
import { Route as AuthedAdminBoundariesRouteImport } from './routes/_authed/admin/boundaries'
import { Route as AuthedAdminComputersRouteImport } from './routes/_authed/admin/computers'
import { Route as AuthedAdminCredentialsRouteImport } from './routes/_authed/admin/credentials'
import { Route as AuthedAdminIdentityProvidersRouteImport } from './routes/_authed/admin/identity-providers'
import { Route as AuthedAdminPeopleRouteImport } from './routes/_authed/admin/people'
import { Route as AuthedAdminPlaygroundRouteImport } from './routes/_authed/admin/playground'
import { Route as AuthedAdminSkillsRouteImport } from './routes/_authed/admin/skills'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedWWorkspaceRouteImport } from './routes/_authed/w/$workspace'
import { Route as AuthedAdminComponentsIndexRouteImport } from './routes/_authed/admin/components/index'
import { Route as AuthedAdminComponentsNameRouteImport } from './routes/_authed/admin/components/$name'
import { Route as AuthedAdminPluginsIndexRouteImport } from './routes/_authed/admin/plugins/index'
import { Route as AuthedAdminPluginsKeyRouteImport } from './routes/_authed/admin/plugins/$key'
import { Route as AuthedSettingsComponentsGalleryIndexRouteImport } from './routes/_authed/settings/components-gallery/index'
import { Route as AuthedSettingsComponentsGalleryNameRouteImport } from './routes/_authed/settings/components-gallery/$name'
import { Route as AuthedSettingsConnectedAccountsIndexRouteImport } from './routes/_authed/settings/connected-accounts/index'
import { Route as AuthedSettingsConnectedAccountsKeyRouteImport } from './routes/_authed/settings/connected-accounts/$key'
import { Route as AuthedWWorkspaceAppRouteImport } from './routes/_authed/w/$workspace/_app'
import { Route as AuthedWWorkspaceAppIndexRouteImport } from './routes/_authed/w/$workspace/_app/index'
import { Route as AuthedWWorkspaceAppBotRouteImport } from './routes/_authed/w/$workspace/_app/bot'
import { Route as AuthedWWorkspaceAppRoutinesRouteImport } from './routes/_authed/w/$workspace/_app/routines'
import { Route as AuthedWWorkspaceAppSkillsRouteImport } from './routes/_authed/w/$workspace/_app/skills'
import { Route as AuthedAdminPluginsKeyToolsToolRouteImport } from './routes/_authed/admin/plugins/$key_.tools.$tool'
import { Route as AuthedWWorkspaceAppAgentsIndexRouteImport } from './routes/_authed/w/$workspace/_app/agents/index'
import { Route as AuthedWWorkspaceAppChannelChannelIdRouteImport } from './routes/_authed/w/$workspace/_app/channel/$channelId'
import { Route as AuthedWWorkspaceAppChannelNewRouteImport } from './routes/_authed/w/$workspace/_app/channel/new'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRouteRoute = AuthedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminAuditRoute = AuthedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminBoundariesRoute = AuthedAdminBoundariesRouteImport.update({
  id: '/boundaries',
  path: '/boundaries',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminComputersRoute = AuthedAdminComputersRouteImport.update({
  id: '/computers',
  path: '/computers',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminCredentialsRoute = AuthedAdminCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminIdentityProvidersRoute =
  AuthedAdminIdentityProvidersRouteImport.update({
    id: '/identity-providers',
    path: '/identity-providers',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)
const AuthedAdminPeopleRoute = AuthedAdminPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminPlaygroundRoute = AuthedAdminPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminSkillsRoute = AuthedAdminSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRouteRoute,
} as any)
const AuthedWWorkspaceRoute = AuthedWWorkspaceRouteImport.update({
  id: '/w/$workspace',
  path: '/w/$workspace',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminComponentsIndexRoute =
  AuthedAdminComponentsIndexRouteImport.update({
    id: '/components/',
    path: '/components/',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)
const AuthedAdminComponentsNameRoute =
  AuthedAdminComponentsNameRouteImport.update({
    id: '/components/$name',
    path: '/components/$name',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)
const AuthedAdminPluginsIndexRoute = AuthedAdminPluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminPluginsKeyRoute = AuthedAdminPluginsKeyRouteImport.update({
  id: '/plugins/$key',
  path: '/plugins/$key',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedSettingsComponentsGalleryIndexRoute =
  AuthedSettingsComponentsGalleryIndexRouteImport.update({
    id: '/components-gallery/',
    path: '/components-gallery/',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)
const AuthedSettingsComponentsGalleryNameRoute =
  AuthedSettingsComponentsGalleryNameRouteImport.update({
    id: '/components-gallery/$name',
    path: '/components-gallery/$name',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)
const AuthedSettingsConnectedAccountsIndexRoute =
  AuthedSettingsConnectedAccountsIndexRouteImport.update({
    id: '/connected-accounts/',
    path: '/connected-accounts/',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)
const AuthedSettingsConnectedAccountsKeyRoute =
  AuthedSettingsConnectedAccountsKeyRouteImport.update({
    id: '/connected-accounts/$key',
    path: '/connected-accounts/$key',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)
const AuthedWWorkspaceAppRoute = AuthedWWorkspaceAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthedWWorkspaceRoute,
} as any)
const AuthedWWorkspaceAppIndexRoute =
  AuthedWWorkspaceAppIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedWWorkspaceAppRoute,
  } as any)
const AuthedWWorkspaceAppBotRoute = AuthedWWorkspaceAppBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => AuthedWWorkspaceAppRoute,
} as any)
const AuthedWWorkspaceAppRoutinesRoute =
  AuthedWWorkspaceAppRoutinesRouteImport.update({
    id: '/routines',
    path: '/routines',
    getParentRoute: () => AuthedWWorkspaceAppRoute,
  } as any)
const AuthedWWorkspaceAppSkillsRoute =
  AuthedWWorkspaceAppSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => AuthedWWorkspaceAppRoute,
  } as any)
const AuthedAdminPluginsKeyToolsToolRoute =
  AuthedAdminPluginsKeyToolsToolRouteImport.update({
    id: '/plugins/$key_/tools/$tool',
    path: '/plugins/$key/tools/$tool',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)
const AuthedWWorkspaceAppAgentsIndexRoute =
  AuthedWWorkspaceAppAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthedWWorkspaceAppRoute,
  } as any)
const AuthedWWorkspaceAppChannelChannelIdRoute =
  AuthedWWorkspaceAppChannelChannelIdRouteImport.update({
    id: '/channel/$channelId',
    path: '/channel/$channelId',
    getParentRoute: () => AuthedWWorkspaceAppRoute,
  } as any)
const AuthedWWorkspaceAppChannelNewRoute =
  AuthedWWorkspaceAppChannelNewRouteImport.update({
    id: '/channel/new',
    path: '/channel/new',
    getParentRoute: () => AuthedWWorkspaceAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/sign': typeof SignRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/onboarding': typeof AuthedOnboardingRoute
  '/admin/audit': typeof AuthedAdminAuditRoute
  '/admin/boundaries': typeof AuthedAdminBoundariesRoute
  '/admin/computers': typeof AuthedAdminComputersRoute
  '/admin/credentials': typeof AuthedAdminCredentialsRoute
  '/admin/identity-providers': typeof AuthedAdminIdentityProvidersRoute
  '/admin/people': typeof AuthedAdminPeopleRoute
  '/admin/playground': typeof AuthedAdminPlaygroundRoute
  '/admin/skills': typeof AuthedAdminSkillsRoute
  '/w/$workspace': typeof AuthedWWorkspaceRouteWithChildren
  '/admin/': typeof AuthedAdminIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/admin/components/$name': typeof AuthedAdminComponentsNameRoute
  '/admin/plugins/$key': typeof AuthedAdminPluginsKeyRoute
  '/settings/components-gallery/$name': typeof AuthedSettingsComponentsGalleryNameRoute
  '/settings/connected-accounts/$key': typeof AuthedSettingsConnectedAccountsKeyRoute
  '/admin/components/': typeof AuthedAdminComponentsIndexRoute
  '/admin/plugins/': typeof AuthedAdminPluginsIndexRoute
  '/settings/components-gallery/': typeof AuthedSettingsComponentsGalleryIndexRoute
  '/settings/connected-accounts/': typeof AuthedSettingsConnectedAccountsIndexRoute
  '/w/$workspace/bot': typeof AuthedWWorkspaceAppBotRoute
  '/w/$workspace/routines': typeof AuthedWWorkspaceAppRoutinesRoute
  '/w/$workspace/skills': typeof AuthedWWorkspaceAppSkillsRoute
  '/w/$workspace/': typeof AuthedWWorkspaceAppIndexRoute
  '/admin/plugins/$key/tools/$tool': typeof AuthedAdminPluginsKeyToolsToolRoute
  '/w/$workspace/channel/$channelId': typeof AuthedWWorkspaceAppChannelChannelIdRoute
  '/w/$workspace/channel/new': typeof AuthedWWorkspaceAppChannelNewRoute
  '/w/$workspace/agents/': typeof AuthedWWorkspaceAppAgentsIndexRoute
}
export interface FileRoutesByTo {
  '/sign': typeof SignRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/': typeof AuthedIndexRoute
  '/admin/audit': typeof AuthedAdminAuditRoute
  '/admin/boundaries': typeof AuthedAdminBoundariesRoute
  '/admin/computers': typeof AuthedAdminComputersRoute
  '/admin/credentials': typeof AuthedAdminCredentialsRoute
  '/admin/identity-providers': typeof AuthedAdminIdentityProvidersRoute
  '/admin/people': typeof AuthedAdminPeopleRoute
  '/admin/playground': typeof AuthedAdminPlaygroundRoute
  '/admin/skills': typeof AuthedAdminSkillsRoute
  '/w/$workspace': typeof AuthedWWorkspaceAppIndexRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/admin/components/$name': typeof AuthedAdminComponentsNameRoute
  '/admin/plugins/$key': typeof AuthedAdminPluginsKeyRoute
  '/settings/components-gallery/$name': typeof AuthedSettingsComponentsGalleryNameRoute
  '/settings/connected-accounts/$key': typeof AuthedSettingsConnectedAccountsKeyRoute
  '/admin/components': typeof AuthedAdminComponentsIndexRoute
  '/admin/plugins': typeof AuthedAdminPluginsIndexRoute
  '/settings/components-gallery': typeof AuthedSettingsComponentsGalleryIndexRoute
  '/settings/connected-accounts': typeof AuthedSettingsConnectedAccountsIndexRoute
  '/w/$workspace/bot': typeof AuthedWWorkspaceAppBotRoute
  '/w/$workspace/routines': typeof AuthedWWorkspaceAppRoutinesRoute
  '/w/$workspace/skills': typeof AuthedWWorkspaceAppSkillsRoute
  '/admin/plugins/$key/tools/$tool': typeof AuthedAdminPluginsKeyToolsToolRoute
  '/w/$workspace/channel/$channelId': typeof AuthedWWorkspaceAppChannelChannelIdRoute
  '/w/$workspace/channel/new': typeof AuthedWWorkspaceAppChannelNewRoute
  '/w/$workspace/agents': typeof AuthedWWorkspaceAppAgentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sign': typeof SignRoute
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/admin/audit': typeof AuthedAdminAuditRoute
  '/_authed/admin/boundaries': typeof AuthedAdminBoundariesRoute
  '/_authed/admin/computers': typeof AuthedAdminComputersRoute
  '/_authed/admin/credentials': typeof AuthedAdminCredentialsRoute
  '/_authed/admin/identity-providers': typeof AuthedAdminIdentityProvidersRoute
  '/_authed/admin/people': typeof AuthedAdminPeopleRoute
  '/_authed/admin/playground': typeof AuthedAdminPlaygroundRoute
  '/_authed/admin/skills': typeof AuthedAdminSkillsRoute
  '/_authed/w/$workspace': typeof AuthedWWorkspaceRouteWithChildren
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/admin/components/$name': typeof AuthedAdminComponentsNameRoute
  '/_authed/admin/plugins/$key': typeof AuthedAdminPluginsKeyRoute
  '/_authed/settings/components-gallery/$name': typeof AuthedSettingsComponentsGalleryNameRoute
  '/_authed/settings/connected-accounts/$key': typeof AuthedSettingsConnectedAccountsKeyRoute
  '/_authed/w/$workspace/_app': typeof AuthedWWorkspaceAppRouteWithChildren
  '/_authed/admin/components/': typeof AuthedAdminComponentsIndexRoute
  '/_authed/admin/plugins/': typeof AuthedAdminPluginsIndexRoute
  '/_authed/settings/components-gallery/': typeof AuthedSettingsComponentsGalleryIndexRoute
  '/_authed/settings/connected-accounts/': typeof AuthedSettingsConnectedAccountsIndexRoute
  '/_authed/w/$workspace/_app/bot': typeof AuthedWWorkspaceAppBotRoute
  '/_authed/w/$workspace/_app/routines': typeof AuthedWWorkspaceAppRoutinesRoute
  '/_authed/w/$workspace/_app/skills': typeof AuthedWWorkspaceAppSkillsRoute
  '/_authed/w/$workspace/_app/': typeof AuthedWWorkspaceAppIndexRoute
  '/_authed/admin/plugins/$key_/tools/$tool': typeof AuthedAdminPluginsKeyToolsToolRoute
  '/_authed/w/$workspace/_app/channel/$channelId': typeof AuthedWWorkspaceAppChannelChannelIdRoute
  '/_authed/w/$workspace/_app/channel/new': typeof AuthedWWorkspaceAppChannelNewRoute
  '/_authed/w/$workspace/_app/agents/': typeof AuthedWWorkspaceAppAgentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign'
    | '/admin'
    | '/settings'
    | '/onboarding'
    | '/admin/audit'
    | '/admin/boundaries'
    | '/admin/computers'
    | '/admin/credentials'
    | '/admin/identity-providers'
    | '/admin/people'
    | '/admin/playground'
    | '/admin/skills'
    | '/w/$workspace'
    | '/admin/'
    | '/settings/'
    | '/admin/components/$name'
    | '/admin/plugins/$key'
    | '/settings/components-gallery/$name'
    | '/settings/connected-accounts/$key'
    | '/admin/components/'
    | '/admin/plugins/'
    | '/settings/components-gallery/'
    | '/settings/connected-accounts/'
    | '/w/$workspace/bot'
    | '/w/$workspace/routines'
    | '/w/$workspace/skills'
    | '/w/$workspace/'
    | '/admin/plugins/$key/tools/$tool'
    | '/w/$workspace/channel/$channelId'
    | '/w/$workspace/channel/new'
    | '/w/$workspace/agents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign'
    | '/onboarding'
    | '/'
    | '/admin/audit'
    | '/admin/boundaries'
    | '/admin/computers'
    | '/admin/credentials'
    | '/admin/identity-providers'
    | '/admin/people'
    | '/admin/playground'
    | '/admin/skills'
    | '/w/$workspace'
    | '/admin'
    | '/settings'
    | '/admin/components/$name'
    | '/admin/plugins/$key'
    | '/settings/components-gallery/$name'
    | '/settings/connected-accounts/$key'
    | '/admin/components'
    | '/admin/plugins'
    | '/settings/components-gallery'
    | '/settings/connected-accounts'
    | '/w/$workspace/bot'
    | '/w/$workspace/routines'
    | '/w/$workspace/skills'
    | '/admin/plugins/$key/tools/$tool'
    | '/w/$workspace/channel/$channelId'
    | '/w/$workspace/channel/new'
    | '/w/$workspace/agents'
  id:
    | '__root__'
    | '/_authed'
    | '/sign'
    | '/_authed/admin'
    | '/_authed/settings'
    | '/_authed/onboarding'
    | '/_authed/'
    | '/_authed/admin/audit'
    | '/_authed/admin/boundaries'
    | '/_authed/admin/computers'
    | '/_authed/admin/credentials'
    | '/_authed/admin/identity-providers'
    | '/_authed/admin/people'
    | '/_authed/admin/playground'
    | '/_authed/admin/skills'
    | '/_authed/w/$workspace'
    | '/_authed/admin/'
    | '/_authed/settings/'
    | '/_authed/admin/components/$name'
    | '/_authed/admin/plugins/$key'
    | '/_authed/settings/components-gallery/$name'
    | '/_authed/settings/connected-accounts/$key'
    | '/_authed/w/$workspace/_app'
    | '/_authed/admin/components/'
    | '/_authed/admin/plugins/'
    | '/_authed/settings/components-gallery/'
    | '/_authed/settings/connected-accounts/'
    | '/_authed/w/$workspace/_app/bot'
    | '/_authed/w/$workspace/_app/routines'
    | '/_authed/w/$workspace/_app/skills'
    | '/_authed/w/$workspace/_app/'
    | '/_authed/admin/plugins/$key_/tools/$tool'
    | '/_authed/w/$workspace/_app/channel/$channelId'
    | '/_authed/w/$workspace/_app/channel/new'
    | '/_authed/w/$workspace/_app/agents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignRoute: typeof SignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/audit': {
      id: '/_authed/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthedAdminAuditRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/boundaries': {
      id: '/_authed/admin/boundaries'
      path: '/boundaries'
      fullPath: '/admin/boundaries'
      preLoaderRoute: typeof AuthedAdminBoundariesRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/computers': {
      id: '/_authed/admin/computers'
      path: '/computers'
      fullPath: '/admin/computers'
      preLoaderRoute: typeof AuthedAdminComputersRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/credentials': {
      id: '/_authed/admin/credentials'
      path: '/credentials'
      fullPath: '/admin/credentials'
      preLoaderRoute: typeof AuthedAdminCredentialsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/identity-providers': {
      id: '/_authed/admin/identity-providers'
      path: '/identity-providers'
      fullPath: '/admin/identity-providers'
      preLoaderRoute: typeof AuthedAdminIdentityProvidersRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/people': {
      id: '/_authed/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AuthedAdminPeopleRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/playground': {
      id: '/_authed/admin/playground'
      path: '/playground'
      fullPath: '/admin/playground'
      preLoaderRoute: typeof AuthedAdminPlaygroundRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/skills': {
      id: '/_authed/admin/skills'
      path: '/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AuthedAdminSkillsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/w/$workspace': {
      id: '/_authed/w/$workspace'
      path: '/w/$workspace'
      fullPath: '/w/$workspace'
      preLoaderRoute: typeof AuthedWWorkspaceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/components/': {
      id: '/_authed/admin/components/'
      path: '/components'
      fullPath: '/admin/components/'
      preLoaderRoute: typeof AuthedAdminComponentsIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/components/$name': {
      id: '/_authed/admin/components/$name'
      path: '/components/$name'
      fullPath: '/admin/components/$name'
      preLoaderRoute: typeof AuthedAdminComponentsNameRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/plugins/': {
      id: '/_authed/admin/plugins/'
      path: '/plugins'
      fullPath: '/admin/plugins/'
      preLoaderRoute: typeof AuthedAdminPluginsIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/plugins/$key': {
      id: '/_authed/admin/plugins/$key'
      path: '/plugins/$key'
      fullPath: '/admin/plugins/$key'
      preLoaderRoute: typeof AuthedAdminPluginsKeyRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/settings/components-gallery/': {
      id: '/_authed/settings/components-gallery/'
      path: '/components-gallery'
      fullPath: '/settings/components-gallery/'
      preLoaderRoute: typeof AuthedSettingsComponentsGalleryIndexRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/components-gallery/$name': {
      id: '/_authed/settings/components-gallery/$name'
      path: '/components-gallery/$name'
      fullPath: '/settings/components-gallery/$name'
      preLoaderRoute: typeof AuthedSettingsComponentsGalleryNameRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/connected-accounts/': {
      id: '/_authed/settings/connected-accounts/'
      path: '/connected-accounts'
      fullPath: '/settings/connected-accounts/'
      preLoaderRoute: typeof AuthedSettingsConnectedAccountsIndexRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/connected-accounts/$key': {
      id: '/_authed/settings/connected-accounts/$key'
      path: '/connected-accounts/$key'
      fullPath: '/settings/connected-accounts/$key'
      preLoaderRoute: typeof AuthedSettingsConnectedAccountsKeyRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/w/$workspace/_app': {
      id: '/_authed/w/$workspace/_app'
      path: ''
      fullPath: '/w/$workspace'
      preLoaderRoute: typeof AuthedWWorkspaceAppRouteImport
      parentRoute: typeof AuthedWWorkspaceRoute
    }
    '/_authed/w/$workspace/_app/': {
      id: '/_authed/w/$workspace/_app/'
      path: '/'
      fullPath: '/w/$workspace/'
      preLoaderRoute: typeof AuthedWWorkspaceAppIndexRouteImport
      parentRoute: typeof AuthedWWorkspaceAppRoute
    }
    '/_authed/w/$workspace/_app/bot': {
      id: '/_authed/w/$workspace/_app/bot'
      path: '/bot'
      fullPath: '/w/$workspace/bot'
      preLoaderRoute: typeof AuthedWWorkspaceAppBotRouteImport
      parentRoute: typeof AuthedWWorkspaceAppRoute
    }
    '/_authed/w/$workspace/_app/routines': {
      id: '/_authed/w/$workspace/_app/routines'
      path: '/routines'
      fullPath: '/w/$workspace/routines'
      preLoaderRoute: typeof AuthedWWorkspaceAppRoutinesRouteImport
      parentRoute: typeof AuthedWWorkspaceAppRoute
    }
    '/_authed/w/$workspace/_app/skills': {
      id: '/_authed/w/$workspace/_app/skills'
      path: '/skills'
      fullPath: '/w/$workspace/skills'
      preLoaderRoute: typeof AuthedWWorkspaceAppSkillsRouteImport
      parentRoute: typeof AuthedWWorkspaceAppRoute
    }
    '/_authed/admin/plugins/$key_/tools/$tool': {
      id: '/_authed/admin/plugins/$key_/tools/$tool'
      path: '/plugins/$key/tools/$tool'
      fullPath: '/admin/plugins/$key/tools/$tool'
      preLoaderRoute: typeof AuthedAdminPluginsKeyToolsToolRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/w/$workspace/_app/agents/': {
      id: '/_authed/w/$workspace/_app/agents/'
      path: '/agents'
      fullPath: '/w/$workspace/agents/'
      preLoaderRoute: typeof AuthedWWorkspaceAppAgentsIndexRouteImport
      parentRoute: typeof AuthedWWorkspaceAppRoute
    }
    '/_authed/w/$workspace/_app/channel/$channelId': {
      id: '/_authed/w/$workspace/_app/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/w/$workspace/channel/$channelId'
      preLoaderRoute: typeof AuthedWWorkspaceAppChannelChannelIdRouteImport
      parentRoute: typeof AuthedWWorkspaceAppRoute
    }
    '/_authed/w/$workspace/_app/channel/new': {
      id: '/_authed/w/$workspace/_app/channel/new'
      path: '/channel/new'
      fullPath: '/w/$workspace/channel/new'
      preLoaderRoute: typeof AuthedWWorkspaceAppChannelNewRouteImport
      parentRoute: typeof AuthedWWorkspaceAppRoute
    }
  }
}

interface AuthedAdminRouteRouteChildren {
  AuthedAdminAuditRoute: typeof AuthedAdminAuditRoute
  AuthedAdminBoundariesRoute: typeof AuthedAdminBoundariesRoute
  AuthedAdminComputersRoute: typeof AuthedAdminComputersRoute
  AuthedAdminCredentialsRoute: typeof AuthedAdminCredentialsRoute
  AuthedAdminIdentityProvidersRoute: typeof AuthedAdminIdentityProvidersRoute
  AuthedAdminPeopleRoute: typeof AuthedAdminPeopleRoute
  AuthedAdminPlaygroundRoute: typeof AuthedAdminPlaygroundRoute
  AuthedAdminSkillsRoute: typeof AuthedAdminSkillsRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedAdminComponentsNameRoute: typeof AuthedAdminComponentsNameRoute
  AuthedAdminPluginsKeyRoute: typeof AuthedAdminPluginsKeyRoute
  AuthedAdminComponentsIndexRoute: typeof AuthedAdminComponentsIndexRoute
  AuthedAdminPluginsIndexRoute: typeof AuthedAdminPluginsIndexRoute
  AuthedAdminPluginsKeyToolsToolRoute: typeof AuthedAdminPluginsKeyToolsToolRoute
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminAuditRoute: AuthedAdminAuditRoute,
  AuthedAdminBoundariesRoute: AuthedAdminBoundariesRoute,
  AuthedAdminComputersRoute: AuthedAdminComputersRoute,
  AuthedAdminCredentialsRoute: AuthedAdminCredentialsRoute,
  AuthedAdminIdentityProvidersRoute: AuthedAdminIdentityProvidersRoute,
  AuthedAdminPeopleRoute: AuthedAdminPeopleRoute,
  AuthedAdminPlaygroundRoute: AuthedAdminPlaygroundRoute,
  AuthedAdminSkillsRoute: AuthedAdminSkillsRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedAdminComponentsNameRoute: AuthedAdminComponentsNameRoute,
  AuthedAdminPluginsKeyRoute: AuthedAdminPluginsKeyRoute,
  AuthedAdminComponentsIndexRoute: AuthedAdminComponentsIndexRoute,
  AuthedAdminPluginsIndexRoute: AuthedAdminPluginsIndexRoute,
  AuthedAdminPluginsKeyToolsToolRoute: AuthedAdminPluginsKeyToolsToolRoute,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

interface AuthedSettingsRouteRouteChildren {
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedSettingsComponentsGalleryNameRoute: typeof AuthedSettingsComponentsGalleryNameRoute
  AuthedSettingsConnectedAccountsKeyRoute: typeof AuthedSettingsConnectedAccountsKeyRoute
  AuthedSettingsComponentsGalleryIndexRoute: typeof AuthedSettingsComponentsGalleryIndexRoute
  AuthedSettingsConnectedAccountsIndexRoute: typeof AuthedSettingsConnectedAccountsIndexRoute
}

const AuthedSettingsRouteRouteChildren: AuthedSettingsRouteRouteChildren = {
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedSettingsComponentsGalleryNameRoute:
    AuthedSettingsComponentsGalleryNameRoute,
  AuthedSettingsConnectedAccountsKeyRoute:
    AuthedSettingsConnectedAccountsKeyRoute,
  AuthedSettingsComponentsGalleryIndexRoute:
    AuthedSettingsComponentsGalleryIndexRoute,
  AuthedSettingsConnectedAccountsIndexRoute:
    AuthedSettingsConnectedAccountsIndexRoute,
}

const AuthedSettingsRouteRouteWithChildren =
  AuthedSettingsRouteRoute._addFileChildren(AuthedSettingsRouteRouteChildren)

interface AuthedWWorkspaceAppRouteChildren {
  AuthedWWorkspaceAppBotRoute: typeof AuthedWWorkspaceAppBotRoute
  AuthedWWorkspaceAppRoutinesRoute: typeof AuthedWWorkspaceAppRoutinesRoute
  AuthedWWorkspaceAppSkillsRoute: typeof AuthedWWorkspaceAppSkillsRoute
  AuthedWWorkspaceAppIndexRoute: typeof AuthedWWorkspaceAppIndexRoute
  AuthedWWorkspaceAppChannelChannelIdRoute: typeof AuthedWWorkspaceAppChannelChannelIdRoute
  AuthedWWorkspaceAppChannelNewRoute: typeof AuthedWWorkspaceAppChannelNewRoute
  AuthedWWorkspaceAppAgentsIndexRoute: typeof AuthedWWorkspaceAppAgentsIndexRoute
}

const AuthedWWorkspaceAppRouteChildren: AuthedWWorkspaceAppRouteChildren = {
  AuthedWWorkspaceAppBotRoute: AuthedWWorkspaceAppBotRoute,
  AuthedWWorkspaceAppRoutinesRoute: AuthedWWorkspaceAppRoutinesRoute,
  AuthedWWorkspaceAppSkillsRoute: AuthedWWorkspaceAppSkillsRoute,
  AuthedWWorkspaceAppIndexRoute: AuthedWWorkspaceAppIndexRoute,
  AuthedWWorkspaceAppChannelChannelIdRoute:
    AuthedWWorkspaceAppChannelChannelIdRoute,
  AuthedWWorkspaceAppChannelNewRoute: AuthedWWorkspaceAppChannelNewRoute,
  AuthedWWorkspaceAppAgentsIndexRoute: AuthedWWorkspaceAppAgentsIndexRoute,
}

const AuthedWWorkspaceAppRouteWithChildren =
  AuthedWWorkspaceAppRoute._addFileChildren(AuthedWWorkspaceAppRouteChildren)

interface AuthedWWorkspaceRouteChildren {
  AuthedWWorkspaceAppRoute: typeof AuthedWWorkspaceAppRouteWithChildren
}

const AuthedWWorkspaceRouteChildren: AuthedWWorkspaceRouteChildren = {
  AuthedWWorkspaceAppRoute: AuthedWWorkspaceAppRouteWithChildren,
}

const AuthedWWorkspaceRouteWithChildren =
  AuthedWWorkspaceRoute._addFileChildren(AuthedWWorkspaceRouteChildren)

interface AuthedRouteChildren {
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
  AuthedSettingsRouteRoute: typeof AuthedSettingsRouteRouteWithChildren
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedWWorkspaceRoute: typeof AuthedWWorkspaceRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
  AuthedSettingsRouteRoute: AuthedSettingsRouteRouteWithChildren,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedWWorkspaceRoute: AuthedWWorkspaceRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignRoute: SignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
