// NOTOS: no tenant package any more; the brand is the deployment's own (stap 2).
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const projectRoot = resolve(import.meta.dir, "..");
const applicationConfiguration = {
  brand: {
    tenantId: process.env.DEPLOYMENT_ID ?? "notos-bots",
    productName: process.env.PRODUCT_NAME ?? "NOTOS Bots",
  },
};
const outputPath = resolve(
  projectRoot,
  "app/src/lib/generated/application-config.ts",
);

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  [
    "// This file is generated by scripts/generate-app-config.ts. Do not edit it.",
    "export type AppConfig = { brand: { tenantId: string; productName: string } };",
    `export const appConfig: AppConfig = ${JSON.stringify(applicationConfiguration, null, 2)};`,
    "",
  ].join("\n"),
);
